<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MUM02L7699" name="Login and Update Profile Test" tests="2" failures="1" timestamp="31 Oct 2019 14:39:29 GMT" time="32.961" errors="0">
  <testcase name="feature" time="0.294" classname="runner.TestRunner"/>
  <testcase name="feature" time="31.987" classname="runner.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: Save as draft is displayed expected [SAVE AS ] but found [SAVE AS DRAFT]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: Save as draft is displayed expected [SAVE AS ] but found [SAVE AS DRAFT]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at runner.TestRunner.feature(TestRunner.java:54)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: Save as draft is displayed expected [SAVE AS ] but found [SAVE AS DRAFT]
	at steps.demo.verify_Save_As_Draft_button_is_visible(demo.java:58)
	at âœ½.Then Verify Save As Draft button is visible(features/demo.feature:29)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Login and Update Profile Test -->
